---
- hosts: home_server
  name: Updating packages and installing docker
  strategy: linear
  roles:
    - role: common
      tags:
        - common
    - role: docker
      tags:
        - docker

- hosts: home_server
  name: Install Home Server's containers
  strategy: free
  roles:
    - role: traefik
      tags:
        - traefik
    - role: homepage
      tags:
        - homepage
    - role: wireguard-server
      tags:
        - wireguard-server
    - role: nextcloud
      tags:
        - nextcloud
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: cloudflare-ddns
      tags:
        - cloudflare-ddns
