---
- hosts: home_server
  name: Updating packages and installing docker
  strategy: linear
  roles:
    - role: common
      tags:
        - common
    - role: docker
      tags:
        - docker

- hosts: home_server
  name: Install Home Server's containers
  roles:
    - role: traefik
      tags:
        - traefik
    - role: homepage
      tags:
        - homepage
    - role: wireguard_server
      tags:
        - wireguard_server
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: cloudflare_ddns
      tags:
        - cloudflare_ddns
    - role: stremio
      tags:
        - stremio
    - role: rdt_client
      tags:
        - rdt_client
